### ISSUE TITLE
memory-version中没有server.cc

### ISSUE THREAD

**Issue by zhangzhongjun** [BintaSong/DistSSE#1]
在memory-version/run.sh中，有使用g++编译server.cc的语句，但是在该文件夹没有找到server.cc这个文件

我也是研究SSE，现在是研究生，如果可能的话希望能与您交流一下

**Comment by BintaSong** [comment]
run.sh是早期遗留的东西，可能是后来忘记删除了。编译的话，都是以Makefile为准

**Comment by zhangzhongjun** [comment]
使用make命令来编译代码
