### ISSUE TITLE
如何运行sophos的代码

### ISSUE THREAD

**Issue by zhangzhongjun** [BintaSong/DistSSE#2]
我可以使用scons构建好sophos，但是当我运行./bench_1e5.sh 时候，会抛出“metadata file does not exist”

**Comment by zhangzhongjun** [comment]
问题补充：已经通过./server -b 14e5.ssdb打开服务器端代码了

**Comment by BintaSong** [comment]
bench_1e5只执行搜索，因此client需要先初始化数据库，比如通过./client -b 14e5.csdb -r
10000初始化10000条index; 然后尝试运行bench_1e5.sh

**Comment by zhangzhongjun** [comment]
首先需要启动服务器，然后再启动客户端
