### ISSUE TITLE
怎么run这个程序

### ISSUE THREAD

**Issue by qahehe** [BintaSong/DistSSE#3]
![Screenshot from 2020-10-01 09-51-27](https://user-images.githubusercontent.com/25258443/94757091-e6c75680-03cb-11eb-89d1-0859673e44e4.png)

如图，我在ubuntu下安装了rocksdb5.7, grpc protoc 3.13.3 ,g++ 9.3.0 
但是make完memory-version后，启动rpc_server 报错argc error，
能否请教一下整个方案的整体运行步骤，小弟我刚开始研究SSE方案，还不是太懂，谢谢大佬

**Comment by BintaSong** [comment]
先在一个终端执行 ./rpc_server  [number of threads]，比如./rpc_server 4，这里4代表线程数量；
然后另外一个终端开启 ./rpc_client [db path]  [number of enrties] [keyword] [number of threads]， 比如./rpc_client  ./testdb 100000 Group-10^1_0_1  4, 具体的参数和关键字格式，请参考rpc_client.cc和DistSSE.db_generator.h中的定义

**Comment by qahehe** [comment]
谢谢大佬，已经解决了！！！
